name: Format

on:
  pull_request:
    types: [converted_to_draft]

permissions:
  contents: write

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - uses: creyD/prettier_action@v4.2
        with:
          prettier_options: --write **/*.{md,yaml}
