name: Hello

on:
  pull_request:
    types: [ready_for_review, opened, reopened, synchronize]

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - run: cat $GITHUB_EVENT_PATH
      - run: echo 'hello'
