name: Prettier

on:
  pull_request:
    types: [ready_for_review, opened, reopened, synchronize]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - uses: creyD/prettier_action@v4.2
        with:
          dry: True
          prettier_options: --check **/*.{md,yaml}
